// <auto-generated />
using GoodHamburger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodHamburger.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422040945_PedidoUpdate")]
    partial class PedidoUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburger.Features.Pedido.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("SanduicheId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SanduicheId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GoodHamburger.Features.Produtos.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.Property<int>("AcompanhamentosId")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.HasKey("AcompanhamentosId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoProduto");
                });

            modelBuilder.Entity("GoodHamburger.Features.Pedido.Models.Pedido", b =>
                {
                    b.HasOne("GoodHamburger.Features.Produtos.Models.Produto", "Sanduiche")
                        .WithMany()
                        .HasForeignKey("SanduicheId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sanduiche");
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.HasOne("GoodHamburger.Features.Produtos.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("AcompanhamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodHamburger.Features.Pedido.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
