// <auto-generated />
using GoodHamburger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodHamburger.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburger.Features.Pedido.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcompanhamentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("BebidaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SanduicheId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcompanhamentoId");

                    b.HasIndex("BebidaId");

                    b.HasIndex("SanduicheId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GoodHamburger.Features.Produtos.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GoodHamburger.Features.Pedido.Models.Pedido", b =>
                {
                    b.HasOne("GoodHamburger.Features.Produtos.Models.Produto", "Acompanhamento")
                        .WithMany()
                        .HasForeignKey("AcompanhamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoodHamburger.Features.Produtos.Models.Produto", "Bebida")
                        .WithMany()
                        .HasForeignKey("BebidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoodHamburger.Features.Produtos.Models.Produto", "Sanduiche")
                        .WithMany()
                        .HasForeignKey("SanduicheId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Acompanhamento");

                    b.Navigation("Bebida");

                    b.Navigation("Sanduiche");
                });
#pragma warning restore 612, 618
        }
    }
}
